team: sn-digital
pipeline: owasp-dependency-reporter
platform: actions
slack_channel: "#http4k-sn"

triggers:
  - type: git
    shallow: true
    watched_paths:
      - etc/owasp-security-checks
      - build.gradle
      - settings.gradle
  - type: timer
    cron: "0 0 * * *"

tasks:
  - name: owasp-security-report
    type: run
    script: \generate-and-send-report
    docker:
      image: eu.gcr.io/halfpipe-io/owasp-dependency-reporter
    save_artifacts:
      - ../../target/reports/dependency-check-report.json
      - ../../target/reports/dependency-check-report.html
    vars:
      BASE_REPO_DIR: "../../"
      PROJECT_NAME: http4k-sn-template
      SLACK_CHANNEL: http4k-sn
      SLACK_OAUTH_TOKEN: ((/springernature/data/shared/PPG-owasp-dependency-reporter slack-oauth-token))
      IGNORE_ZERO_ISSUES: true
