version: '3'
services:
  app:
    image: eu.gcr.io/halfpipe-io/build-openjdk17
    command: ./build
    working_dir: /root/code
    volumes:
      - .:/root/code:delegated
      - $HOME/.gradle:/root/.gradle:delegated
